<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    // MyPromise.js

    // 先定义三个常量表示状态
    const PENDING = 'pending';
    const FULFILLED = 'fulfilled';
    const REJECTED = 'rejected';

    // 新建 MyPromise 类
    class MyPromise {
      constructor(executor) {
        // executor 是一个执行器，进入会立即执行
        // 并传入resolve和reject方法
        try {
          executor(this.resolve, this.reject)
        } catch (e) {
          this.reject(e)
        }
      }

      // 储存状态的变量，初始值是 pending
      status = PENDING;

      // resolve和reject为什么要用箭头函数？
      // 如果直接调用的话，普通函数this指向的是window或者undefined
      // 用箭头函数就可以让this指向当前实例对象
      // 成功之后的值
      value = null;
      // 失败之后的原因
      reason = null;

      // MyPromise 类中新增
      // 存储成功回调函数
      onFulfilledCallbacks = [];
      // 存储失败回调函数
      onRejectedCallbacks = [];

      // 更改成功后的状态
      resolve = (value) => {
        // 只有状态是等待，才执行状态修改
        if (this.status === PENDING) {
          // 状态修改为成功
          this.status = FULFILLED;
          // 保存成功之后的值
          this.value = value;

          // resolve里面将所有成功的回调拿出来执行
          while (this.onFulfilledCallbacks.length) {
            // Array.shift() 取出数组第一个元素，然后（）调用，shift不是纯函数，取出后，数组将失去该元素，直到数组为空
            this.onFulfilledCallbacks.shift()(value)
          }
        }
      }

      // 更改失败后的状态
      reject = (reason) => {
        // 只有状态是等待，才执行状态修改
        if (this.status === PENDING) {
          // 状态成功为失败
          this.status = REJECTED;
          // 保存失败后的原因
          this.reason = reason;

          while (this.onRejectedCallbacks.length) {
            this.onRejectedCallbacks.shift()(reason)
          }

        }
      }

      then(onFulfilled, onRejected) {
        onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : value => value;
        onRejected = typeof onRejected === 'function' ? onRejected : reason => { throw reason };

        // ==== 新增 ====
        // 为了链式调用这里直接创建一个 MyPromise，并在后面 return 出去
        const promise2 = new MyPromise((resolve, reject) => {
          // 这里的内容在执行器中，会立即执行
          if (this.status === FULFILLED) {
            queueMicrotask(() => {
              try {
                // 获取成功回调函数的执行结果
                const x = onFulfilled(this.value);
                // 传入 resolvePromise 集中处理
                resolvePromise(promise2, x, resolve, reject);
              } catch (e) {
                reject(e)
                // onRejected(e) 
                /**
                 * 不能是 onRejected
                 * 因为 状态是 FULFILLED，说明已经更改过了
                 * 而promise状态只会有一种，在onRejected就会执行失败的代码，之前已经执行过了或之前执行过成功的代码就不是只会执行成功或者失败了
                */
              }
            })
          } else if (this.status === REJECTED) {
            queueMicrotask(() => {
              try {
                const x = onRejected(this.reason)
                resolvePromise(promise2, x, resolve, reject);
              } catch (e) {
                reject(e)
              }
            })
            // onRejected(this.reason);
          } else if (this.status === PENDING) {
            this.onFulfilledCallbacks.push(() => {
              queueMicrotask(() => {
                try {
                  const x = onFulfilled(this.value);
                  resolvePromise(promise2, x, resolve, reject);
                } catch (e) {
                  reject(e)
                }

              })
            });
            this.onRejectedCallbacks.push(() => {
              queueMicrotask(() => {
                try {
                  const x = onRejected(this.reason)
                  resolvePromise(promise2, x, resolve, reject);
                } catch (e) {
                  reject(e)
                }

              })
            });
          }
        })

        return promise2;


        // 判断状态
        // if (this.status === FULFILLED) {
        //   // 调用成功回调，并且把值返回
        //   onFulfilled(this.value);
        // } else if (this.status === REJECTED) {
        //   // 调用失败回调，并且把原因返回
        //   onRejected(this.reason);
        // } else if (this.status === PENDING) {
        //   this.onFulfilledCallbacks.push(onFulfilled)
        //   this.onRejectedCallbacks.push(onRejected)
        // }
      }

      static resolve(value) {
        if (value instanceof MyPromise) {
          return value
        }
        return new MyPromise(r => r(value))
      }

      static reject(e) {
        // 这里判断是一个myPromise实例，返回的话就会就是返回的实例，不一定是reject,所以要包一层确认是rejection
        return new MyPromise((r, j) => j(e))
      }
    }
    // function resolvePromise(promise2, x, resolve, reject) {
    //   // 判断x是不是 MyPromise 实例对象
    //   if (promise2 === x) {
    //     return reject(new TypeError('same Promise'))
    //   }
    //   if (x instanceof MyPromise) {
    //     // 执行 x，调用 then 方法，目的是将其状态变为 fulfilled 或者 rejected
    //     // x.then(value => resolve(value), reason => reject(reason))
    //     // 简化之后
    //     x.then(resolve, reject)
    //   } else {
    //     // 普通值
    //     resolve(x)
    //   }
    // }

  </script>
  <!-- <script>
    // test.js

    const promise = new MyPromise((resolve, reject) => {
      // 目前这里只处理同步的问题
      resolve('success')
    })

    function other() {
      return new MyPromise((resolve, reject) => {
        reject('other')
      })
    }
    promise.then(value => {
      console.log(1)
      console.log('resolve', value)
      return other()
      return 'xixi'
    }).then(value => {
      console.log(2)
      console.log('resolve', value)
    }, (e)=>{
      console.log('e' + e)
    }).then(value => {
      console.log(3)
      console.log('resolve3', value)
    }, (e)=>{
      console.log('e2' + e)
    })


  </script> -->
  <script>
    // const promise = new MyPromise((r, j) => { j(123) })
    // const gzp = promise.then(value => {
    //   console.log(1)
    //   console.log('resolve', value)
    //   throw new Error('then error')
    // }, reason => {
    //   console.log(2)
    //   console.log(reason)
    // })

    // gzp.then(value => {
    //   console.log(3)
    //   console.log(value);
    // }, reason => {
    //   console.log(4)
    //   console.log(reason)
    // })

    // MyPromise.resolve('456789').then((d) => { console.log(d + 'ddd') })

    // // var errPromise = Promise.reject('err')
    // MyPromise.reject(MyPromise.resolve(1)).then(d => { console.log(d + '123456789') }, e => {

    //   console.log('ee' + e)
    // })


    // MyPromise.js

    function resolvePromise(promise, x, resolve, reject) {
      // 如果相等了，说明return的是自己，抛出类型错误并返回
      if (promise === x) {
        return reject(new TypeError('The promise and the return value are the same'));
      }

      if (typeof x === 'object' || typeof x === 'function') {
        // x 为 null 直接返回，走后面的逻辑会报错
        if (x === null) {
          return resolve(x);
        }

        let then;
        try {
          // 把 x.then 赋值给 then 
          then = x.then;
        } catch (error) {
          // 如果取 x.then 的值时抛出错误 error ，则以 error 为据因拒绝 promise
          return reject(error);
        }

        // 如果 then 是函数
        if (typeof then === 'function') {
          let called = false;
          try {
            then.call(
              x, // this 指向 x
              // 如果 resolvePromise 以值 y 为参数被调用，则运行 [[Resolve]](promise, y)
              y => {
                // 如果 resolvePromise 和 rejectPromise 均被调用，
                // 或者被同一参数调用了多次，则优先采用首次调用并忽略剩下的调用
                // 实现这条需要前面加一个变量 called
                if (called) return;
                called = true;
                resolvePromise(promise, y, resolve, reject);
              },
              // 如果 rejectPromise 以据因 r 为参数被调用，则以据因 r 拒绝 promise
              r => {
                if (called) return;
                called = true;
                reject(r);
              });
          } catch (error) {
            // 如果调用 then 方法抛出了异常 error：
            // 如果 resolvePromise 或 rejectPromise 已经被调用，直接返回
            if (called) return;

            // 否则以 error 为据因拒绝 promise
            reject(error);
          }
        } else {
          // 如果 then 不是函数，以 x 为参数执行 promise
          resolve(x);
        }
      } else {
        // 如果 x 不为对象或者函数，以 x 为参数执行 promise
        resolve(x);
      }
    }

  </script>

  <script>
    // const MyPromise = require('./MyPromise.js')

    // MyPromise.resolve().then(() => {
    //   console.log(0);
    //   return MyPromise.resolve(4);
    // }).then((res) => {
    //   console.log(res)
    // })

    // new MyPromise(() => {
    //   console.log(-1)
    // })

    // console.log(1)

// MyPromise.resolve().then(() => {
//   console.log(1);
// }).then(() => {
//   console.log(2);
// }).then(() => {
//   console.log(3);
// }).then(() => {
//   console.log(5);
// }).then(() =>{
//   console.log(6);
// })

  </script>

  <script>
    MyPromise.resolve().then(() => {
      console.log(1);
      return MyPromise.resolve(2) // 
      /**
       * 执行console.log之后。注册一个微任务 （相当于把y => {
                if (called) return;
                called = true;
                resolvePromise(promise, y, resolve, reject);
              }这一坨返回微任务）
       * 下一轮 微任务执行时 就执行上面的resolvePromise
              发现结果是2直接 resolve。 resolve时又会触发console.log(res)这个回调。放入微任务队列
       * 所以 console.log(res) 其实在下下次微任务
      * */
    }).then(res => {
      console.log(res)
    })

    MyPromise.resolve().then(() => {
      console.log(10); // 把20的微任务放入队列
    }).then(() => {
      console.log(20);
    }).then(() => {
      console.log(30);
    }).then(() => {
      console.log(40);
    })

    console.log('0')

    // 0 1 10 20 2 30 40
    /**
     * MyPromise.resolve 执行 then 入队
    */
  </script>
  <script>
    Promise.resolve().then(() => {
      console.log(1);
      return Promise.resolve(2).then(res => {
        return res // 1.1
      });
    }).then(res => {
      console.log(res)
    })

    Promise.resolve().then(() => {
      console.log(10);
    }).then(() => {
      console.log(20);
    }).then(() => {
      console.log(30);
    }).then(() => {
      console.log(40);
    })

    console.log(0)

    // 0 1 10 return 20 30 2 40 
  </script>


  <script>

    async function async1() {
      console.log(1);
      await async2();
      console.log(2);
    }
    async function async2() {
      console.log(3);
    }
    async1();

    new Promise(resolve => {
      console.log(10);
      resolve();
    }).then(() => {
      console.log(20);
    }).then(() => {
      console.log(30)
    }).then(() => {
      console.log(40)
    })
  </script>
</body>

</html>